### ISSUE TITLE
Why not develop in accordance with most Python specifications?

### ISSUE THREAD

**Issue by timmy61109** [IIT-EnergySystemModels/openTEPES#51]
你們好，我是一開始幫你們解決pytest和lint的人，以為之後這個專案發展上不離Python社群的開發方式太遠，現在發現有許多不太一致的地方。我希望後續其他python開發者也可以容易的參與開發。

我不會強迫，只是好心提醒。

Hello, I was the one who helped you solve pytest and lint at the beginning. I thought that the development of this project will not be too far away from the development method of the Python community. Now I find that there are many inconsistencies. I hope that other python developers can easily participate in the development.

I will not force, just kindly remind.

**Comment by erikfilias** [comment]
Hi @timmy61109,  thanks for your comment.
We tried to follow some specifications but preserve most lessons learned from GAMS about formulation and coding in power system optimization problems.
Could you give us a brief list of the inconsistencies, please?
And, we'll try to solve it.
Thank you so much for your attention and participation.

**Comment by timmy61109** [comment]
I think there are two main points:

1. `doc` --> `docs`

**Comment by timmy61109** [comment]
By the way, it is recommended to use rebase when merging and then merge, which will bring tidiness and cleanliness to the development branch.
