### ISSUE TITLE
`openTEPES_run` fails with CBC and GLPK solvers

### ISSUE THREAD

**Issue by pgoiporia** [IIT-EnergySystemModels/openTEPES#55]
I tried running the 9n case tutorial notebook and failed to build the model. These are the parameters I used.
![Screenshot from 2024-01-19 15-31-28](https://github.com/IIT-EnergySystemModels/openTEPES/assets/85507449/76a033f9-272f-44d6-a77c-7a4d8a378645)

I received the following output.
![Screenshot from 2024-01-19 15-32-21](https://github.com/IIT-EnergySystemModels/openTEPES/assets/85507449/5d546c36-c76b-4760-b9fb-7f80f885fd56)

I poked around the codebase a bit, and it looks like the `ProblemSolving` function in `openTEPES_ProblemSolving.py` only produces a `SolverResults` object if `SolverName` is gams or gurobi, both of which require commercial/academic licenses to use. I was hoping to use CBC or GLPK as they are open source and I have access to them.

**Comment by erikfilias** [comment]
Hi @pgoiporia, I just made some updates in ProblemSolving to use any open solver. 
In '01-openTEPES-Demo.ipynb' from [openTEPES-tutorial](https://github.com/IIT-EnergySystemModels/openTEPES-tutorial/blob/main/notebooks/01-openTEPES-Demo.ipynb), you can see that the demo notebook has been updated and it is using the HiGHS solver. I would suggest that you use it. According to the setting of the '9n' case, the demo example should work with the 2Gb memory.  Please try it, and let us know if it is working.

![image](https://github.com/IIT-EnergySystemModels/openTEPES/assets/8010477/865c7ad8-25fc-4462-b82e-a9f38b6eb4e8)
![image](https://github.com/IIT-EnergySystemModels/openTEPES/assets/8010477/a87831ff-6d64-456d-bed2-5e83a3223c7b)

**Comment by pgoiporia** [comment]
Hey @erikfilias . Thanks for the quick response! This was working, but I'm running into the following error now.
![image](https://github.com/IIT-EnergySystemModels/openTEPES/assets/85507449/705fa116-ebaf-43fd-b77b-e23eebe12be9)
![image](https://github.com/IIT-EnergySystemModels/openTEPES/assets/85507449/8489f991-f0bd-4b98-90ac-56d405bc52f2)
Any insights?

**Comment by erikfilias** [comment]
Hi @pgoiporia, Yeah, we needed to update files in the case 9n. Can you try it again, please?
