### ISSUE TITLE
Document difference between `mTEPES` and `OptModel`

### ISSUE THREAD

**Issue by kdheepak** [IIT-EnergySystemModels/openTEPES#71]
Currently there's two variables (`mTEPES` and `OptModel`) that hold a reference to the same pyomo ConcreteModel. Is there a reason there's two variables like so? I changed all instances of `OptModel` to `mTEPES` and was able to get the same results for the tests. 

If there's a reason for having two variables, can you explain the difference? Would it be possible to add it to the documentation?

**Comment by erikfilias** [comment]
Hi @kdheepak, the model is specifically designed to support running multiple simulations in parallel. It's true that there is no documentation of mTEPES and OptModel. In mTEPES, we define sets and parameters, whereas the optmodel is structured around variables and constraints. In essence, the optmodel acts as a framework for dynamically adjusting key variables in memory after the base case has been solved. This setup allows for the efficient exploration of multiple scenarios - such as sensitivities or contingencies - by making targeted adjustments to the parameters within mTEPES. These variations can then be run in parallel, enabling faster analysis and decision-making across multiple conditions. We, @arght and I, will add the description of this feature in the model.

**Comment by kdheepak** [comment]
Thanks for the answer! It'd be great if you can add an example of this to show that this is possible, and a test case to check that this works as expected!
