### ISSUE TITLE
Document core execution

### ISSUE THREAD

**Issue by kdheepak** [IIT-EnergySystemModels/openTEPES#74]
In the following code, there's model formulation + problem solving:

https://github.com/IIT-EnergySystemModels/openTEPES/blob/dcd3019b7a65c75a43a0c3142e9cc3bc062c99a0/openTEPES/openTEPES.py#L78-L196

if I have to summarize this code, I'd say it does the following:

```python
for p, sc, st in mTEPES.ps * mTEPES.stt:
    delete_and_initialize_components(mTEPES, st)
    calculate_load_levels(mTEPES, p, sc, st)
    formulate_objective_and_constraints(mTEPES, p, sc, st)
    solve_problem(mTEPES, p, sc, st)
```

where `solve_problem` is:

```python
def solve_problem(mTEPES, p, sc, st):
    if (len(mTEPES.gc) == 0 or (len(mTEPES.gc) > 0 and mTEPES.pIndBinGenInvest() == 2)) and (len(mTEPES.gd) == 0 or (len(mTEPES.gd) > 0 and mTEPES.pIndBinGenRetire() == 2)) and (len(mTEPES.lc) == 0 or (len(mTEPES.lc) > 0 and mTEPES.pIndBinNetElecInvest() == 2)) and (min([mTEPES.pEmission[p,ar] for ar in mTEPES.ar]) == math.inf or sum(mTEPES.pEmissionRate[nr] for nr in mTEPES.nr) == 0):
        # there are no expansion decisions, or they are ignored (it is an operation planning model)
        mTEPES.pScenProb[p, sc] = 1.0
        ProblemSolving(DirName, CaseName, SolverName, mTEPES, mTEPES, p, sc, st)
        mTEPES.pScenProb[p, sc] = 0.0
        for c in mTEPES.component_objects(pyo.Constraint, active=True):
            if c.name.find(str(p)) != -1 and c.name.find(str(sc)) != -1:
                c.deactivate()
    else:
        if (p, sc) == mTEPES.ps.last() and st == mTEPES.Last_st and mTEPES.NoRepetition == 0:
            mTEPES.NoRepetition = 1
            delete_and_initialize_components(mTEPES, st)
            calculate_load_levels(mTEPES)
            ProblemSolving(DirName, CaseName, SolverName, mTEPES, mTEPES, p, sc, st)
```

I have two questions about this code:

1. Is my understanding correct that the first `if` block of code is called at every stage for just dispatch? 
2. Also, is my understanding correct that the second block of code will only execute at the last stage and last time period, i.e. after the model is fully built?

Let me know if that understanding is correct? If that's not correct, can you elaborate on when this understanding would not be true? 

This is understanding is correct, would you be open to refactoring this code so that it is easier to understand? e.g.:

```python
def pcm()
    for p, sc, st in mTEPES.ps * mTEPES.stt:
        delete_and_initialize_components(mTEPES, st)
        calculate_load_levels(mTEPES, p, sc, st)
        formulate_objective_and_constraints(mTEPES, p, sc, st)
        solve_pcm_problem(mTEPES, p, sc, st)

def capex():
    for p, sc, st in mTEPES.ps * mTEPES.stt:
        delete_and_initialize_components(mTEPES, st)
        calculate_load_levels(mTEPES, p, sc, st)
        formulate_objective_and_constraints(mTEPES, p, sc, st)
    solve_capex_problem(mTEPES, p, sc, st)

def run():
    if is_model_investment():
        capex()
    else:
        pcm()
```

I'm happy to submit a PR for this.

**Comment by erikfilias** [comment]
Hi @kdheepak, 

Thank you for your questions. Let me explain how the code works:

1. **First Block - Dispatch Stage:** Yes, your understanding is correct that the first block of code is executed iteratively for each stage of the model. The code within the loop operates for every **period (p)**, **scenario (sc)**, and **stage (st)**. The hierarchy is as follows: `p` represents a target year (or several years in dynamic planning), `sc` refers to different scenarios within this period, and `st` represents time slices such as representative hours or days. This block helps to define the sets and constraints needed to manage the operation of the system during each phase of the scenario-period combination.

2. **Second Block - Last Stage and Period:** The second block of code will only execute when you reach the last stage (st == mTEPES.Last_st) and last period/scenario ((p,sc) == mTEPES.ps.last()). The condition ensures that this block of code, responsible for aspects like final investment decision updates or writing LP files, only runs once the model has gone through all periods, stages, and scenarios. This typically corresponds to after the entire model has been formulated.

Please, take care of mTEPES.NoRepetition. And, one aspect we are testing in the model is the ability for each period (p) to have different sets of stages, as well as allowing flexibility in the combinations of (p, sc). This should allow for a more detailed and dynamic representation of the operation of the system. For example, the year(s) being analysed may have a different set of representative days or weeks.

@arght, if something is missing, please add it.

**Comment by arght** [comment]
The original idea of this structure was intended/developed for being used with Benders decomposition (Benders decomposition is not currently available under the public verion of openTEPES). However, we wanted to solve the expansion problem with Benders and therefore the master problem determines the investment decisions and subproblems determine the operation decisions. We use the stage for splitting the year allowing parallel solve of the differnet stages of a year. Stages are solved independently. We assume they are not linked among them. A "natural" stage can be a week or a month or a semester. From the point of view of the system we need to see which constraints link stages (weeks, months, etc.) and what simplications are considered if we assume them independent.
In the current public version stages affect only the sequence of how the problem is formulated but has no impact in the solution. Problems are formulated stage by stage (that can be seen in the LP file) but at the end all the stages are included in the optimization problem.
As mentioned by @erikfilias you can define different stages for different periods/scenarios if you want to use a stage for each representative day/week
Hopefully, this can clarify how openTEPES works
Andrés

**Comment by arght** [comment]
The use of NoRepetition as mentioned in the code comments is for fixing some or all the binary variables when detecting if it is the very last period, subperiod and stage.
NoRepetition is like a global variable of control. If you consider that it would be better to code in another fine for me to porpose a PR and implement it
Andrés

**Comment by erikfilias** [comment]
Hi @kdheepak,

Thanks @arght for the clarifications and I agree.

Then, regarding the PR:

We appreciate the suggestion to refactor the code for improved readability. Breaking it down into separate functions certainly seems like a good way to make the logic clearer and more modular. I'd be open to seeing how the proposed changes could streamline the structure, especially for maintainability and clarity.

Feel free to submit a PR, and we can review the changes together to ensure they align with the overall model goals and performance requirements.

Thanks again for your contribution.

**Comment by jarry7** [comment]
Hi @kdheepak  @arght @erikfilias,

Watching this from a distance and it reminded me of the Bender's Decomposition discussion we had previously.  

Is there a specific reason for that not being part of and maintained in the public repository for `openTEPES`?

**Comment by arght** [comment]
@jarry7 
There is no a specific reason for not having Benders decomposition publicly available, but so far:
- we have not needed to use in practice Benders for any case study (Spain, Europe, etc.)
- the implementation we have done is compatible with solving the complete problem and that made it less efficient
- the implementation needs to be improved to be competitive with the direct solution of the problem and that will only happen if we need to solve a real case study that demands that
We are open to work in that direction if really needed
Andrés
