### ISSUE TITLE
pDemandElecPeak calculation does not vary with period

### ISSUE THREAD

**Issue by rachelmoglen** [IIT-EnergySystemModels/openTEPES#78]
`pDemandElecPeak` is calculated in `openTEPES_InputData.py` as follows:

```
pDemandElecPeak          = pd.Series([0.0 for p,ar in mTEPES.par], index=mTEPES.par)
   for p,ar in mTEPES.par:
       # values < 1e-5 times the maximum demand for each area (an area is related to operating reserves procurement, i.e., country) are converted to 0
       pDemandElecPeak[p,ar] = pDemandElec[[nd for nd in d2a[ar]]].sum(axis=1).max()
```

It is my understanding that maximum above is calculated over all periods, not just the rows corresponding to the current value of `p` in each iteration of the for loop. The result is `pDemandElecPeak` is indexed by period `p` but does not vary with `p`. 

Later in `openTEPES_InputData.py`, reserve margin infeasibility is checked:

```
 # detecting reserve margin infeasibility
        for p,ar in mTEPES.p*mTEPES.ar:
            if sum(mTEPES.pRatedMaxPowerElec[g] * mTEPES.pAvailability[g]() / (1.0-mTEPES.pEFOR[g]) for g in mTEPES.g if (p,g) in mTEPES.pg and (ar,g) in mTEPES.a2g) < mTEPES.pDemandElecPeak[p,ar] * mTEPES.pReserveMargin[p,ar]:
                raise ValueError('### Reserve margin infeasibility ', p, ar, sum(mTEPES.pRatedMaxPowerElec[g] * mTEPES.pAvailability[g]() / (1.0-mTEPES.pEFOR[g]) for g in mTEPES.g if (p,g) in mTEPES.pg and (ar,g) in mTEPES.a2g), mTEPES.pDemandElecPeak[p,ar] * mTEPES.pReserveMargin[p,ar])
```
The result of how `pDemandElecPeak` is calculated means that reserve margin infeasibility is detected if any period does not have enough generation to meet the peak demand across all periods, not just that period's peak demand. 

Is this the intended behavior? If not, I suggest the following change or similar to the `pDemandElecPeak` calculation:
```
        # pDemandElecPeak[p,ar] = pDemandElec[[nd for nd in d2a[ar]]].sum(axis=1).max()   #old
        pDemandElecPeak[p, ar] = pDemandElec.xs(key=p, level='Period', drop_level=False)[[nd for nd in d2a[ar]]].sum(axis=1).max()   #fix
```

Thank you for looking into this! Please let me know if I should provide any further context.

**Comment by arght** [comment]
I have reviewed the instruction and changed by this one
pDemandElecPeak[p,ar] = pDemandElec.loc[p, [nd for nd in d2a[ar]]].sum(axis=1).max()
which I think it works.
I have updated it into GitHub

**Comment by rachelmoglen** [comment]
Thanks for looking into this so quickly!

Since `pDemandElec` is multi-indexed, it might be preferable to explicitly acknowledge that:
```
pDemandElecPeak[p,ar] = pDemandElec.loc[p, :, :][[nd for nd in d2a[ar]]].sum(axis=1).max()
```

**Comment by arght** [comment]
Update in GitHub

**Comment by rachelmoglen** [comment]
Great, thanks so much for your responses!
